version: '3'
services:

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  web:
    env_file: .env
    build: beta
    depends_on:
      - pg
    ports:
     - "3333:3333"
    command: ["rails", "server"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  pg:
    env_file: .env
    image: postgres
    volumes:
      - "data:/var/lib/postgresql/data"

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

volumes:
  data:

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
