version: '3'
services:

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  react:
    env_file: .env
    build: alpha
    depends_on:
      - pg
      - rails
    ports:
     - "5555:5555"
    command: ["serve", "-p", "5555", "-s", "build"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  rails:
    env_file: .env
    build: beta
    depends_on:
      - pg
    ports:
     - "3333:3333"
    command: ["rails", "server"]

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

  pg:
    env_file: .env
    image: postgres
    volumes:
      - "data:/var/lib/postgresql/data"

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###

volumes:
  data:

### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
### ----------------------------------------------------------------------- ###
