default: &default
  host: 0.0.0.0
  username: postgres
  password: pass1234
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: health_development
test:
  <<: *default
  database: health_test
production:
  <<: *default
  host: pg
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: health_production
